/**:  
  ros__parameters:
    pid_gains:
      position:
        # -----------------------------------------------------------------
        # 关节 1-4 (大臂)：承重主力
        # 策略：P 值调回 2000 (保证有力气)，但 D 值加倍到 100 (强力刹车，防止抖动)
        # -----------------------------------------------------------------
        fr3_joint1: {p: 2000.0, i: 20.0, d: 100.0}
        fr3_joint2: {p: 2000.0, i: 20.0, d: 100.0}
        fr3_joint3: {p: 2000.0, i: 20.0, d: 100.0}
        fr3_joint4: {p: 2000.0, i: 20.0, d: 100.0}
        
        # -----------------------------------------------------------------
        # 关节 5-6 (手腕)：中等力度
        # 策略：P 值 800 足够了，D 值 40
        # -----------------------------------------------------------------
        fr3_joint5: {p: 800.0, i: 10.0,  d: 40.0}
        fr3_joint6: {p: 800.0, i: 10.0,  d: 40.0}
        
        # -----------------------------------------------------------------
        # 关节 7 (末端)
        # -----------------------------------------------------------------
        fr3_joint7: {p: 200.0, i: 0.0,  d: 10.0}
        
        # 手指
        fr3_finger_joint1: {p: 100.0, i: 0.0, d: 10.0}
        fr3_finger_joint2: {p: 100.0, i: 0.0, d: 10.0}

      velocity:
        fr3_joint1: {p: 10.0, i: 0.0, d: 0.0}