joint1:
  limit:
    lower:      -2.9007
    upper:       2.9007
    velocity:    2.62
    effort:     87.0
  position_based_velocity_limits:
    velocity_offset: 0.6520
    deceleration_limit: 6.0

joint2:
  limit:
    lower:     -1.8361
    upper:      1.8361
    velocity:   2.62
    effort:    87.0
  position_based_velocity_limits:
    velocity_offset: 0.2500
    deceleration_limit: 2.585


joint3:
  limit:
    lower:     -2.9007
    upper:      2.9007
    velocity:   2.62
    effort:    87.0
  position_based_velocity_limits:
    velocity_offset: 0.2005
    deceleration_limit: 3.5


joint4:
  limit:
    lower:     -3.0770
    upper:     -0.1169
    velocity:   2.62
    effort:    87.0
  position_based_velocity_limits:
    velocity_offset: 0.3542
    deceleration_limit: 4.0

joint5:
  limit:
    lower:     -2.8763
    upper:      2.8763
    velocity:   5.26
    effort:    12.0
  position_based_velocity_limits:
    velocity_offset: 0.5738
    deceleration_limit: 17.0

joint6:
  limit:
    lower:      0.4398
    upper:      4.6216
    velocity:   4.18
    effort:    12.0
  position_based_velocity_limits:
    velocity_offset: 0.4885
    deceleration_limit: 5.5

joint7:
  limit:
    lower:     -3.0508
    upper:      3.0508
    velocity:   5.26
    effort:    12.0
  position_based_velocity_limits:
    velocity_offset: 0.4592
    deceleration_limit: 17.0
