cartesian_limits:
  max_trans_vel: 1.0   # 末端移动最大速度 (m/s)
  max_trans_acc: 2.25  # 末端移动最大加速度
  max_trans_dec: 5.0   # 末端移动最大减速度
  max_rot_vel: 1.57    # 末端旋转最大角速度 (rad/s)
  max_rot_acc: 1.5
  max_rot_dec: 1.5